import Home from './Home'
import Header from './Header'
import Contact from './Contact'
import Footer from './Footer'
import Nav from './Nav'
import Project from './Project'
import Portfolio from './Portfolio'